### ISSUE TITLE
نوشته های فارسی رو راستچین بکنید.

### ISSUE THREAD

**Issue by farooqkz** [dddeveloperrr/youtube-leecher#2]
<div style="text-direction: rtl; text-align: right;">در فایل Readme.md لطفا نوشته های فارسی را راستچین بکنید.</div>
باید از تگ های اچ تی ام ال استفاده بکنید.

**Comment by dddeveloperrr** [comment]
سلام داخل نگ 
p
هم گذاشتم ولی بازم درست نشد

<   p style="text-align: right;">به نام خدا</   p>

اینجوری کردم ولی درست نشد

**Comment by farooqkz** [comment]
ببینید این چطور اینکار رو انجام داده:
https://github.com/elyas8702/A-Byte-of-Python-Farsi

**Comment by dddeveloperrr** [comment]
مرسی ممنون

**Comment by farooqkz** [comment]
این روهم ببندم دیگه؟

**Comment by dddeveloperrr** [comment]
بله ممنون
